BEGIN WORK;
CREATE TABLE TEST(ID serial PRIMARY KEY, name VARCHAR(25), city VARCHAR(25));
INSERT INTO TEST(name, city) VALUES('Shailesh', 'NOIDA');
INSERT INTO TEST(name, city) VALUES('SUMIT', 'DELHI');
INSERT INTO TEST(name, city) VALUES('SUNIL', 'CHENNAI');
INSERT INTO TEST(name, city) VALUES('RAVI', 'DELHI');
INSERT INTO TEST(name, city) VALUES('GAURAV', 'NOIDA');
INSERT INTO TEST(name, city) VALUES('MUNNI', 'SKB');
COMMIT;
